### ISSUE TITLE
输出颜色怎么显示出来

### ISSUE THREAD

**Issue by geekonion** [4ch12dy/xia0LLDB#1]
首先给个大大的赞。
Xcode终端输出的时候，颜色没有生效，效果是这样的：
frame #5: [file:[36m0x1814b1a00[0m mem:[2m0x196e65a00[0m] [33mCFNetwork[0m`__75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 32 
请问怎么才能显示出来色彩？

**Comment by 4ch12dy** [comment]
> 首先给个大大的赞。
> Xcode终端输出的时候，颜色没有生效，效果是这样的：
> frame #5: [file:[36m0x1814b1a00[0m mem:[2m0x196e65a00[0m] [33mCFNetwork[0m`__75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 32
> 请问怎么才能显示出来色彩？
感谢支持
Xcode的输出终端不支持颜色输出，在Xcode8以前好像XcodeColors这个插件还能支持。
不过我还是准备加一个参数，如果是在Xcode的时候就不输出颜色，不然反而影响查看其它信息

**Comment by 4ch12dy** [comment]
感谢支持
Xcode的终端不支持颜色输出，sbt命令我更新了-x选项，在Xcode中的时候输入sbt -x禁用颜色输出

**Comment by 4ch12dy** [comment]
@geekonion 
感谢支持
Xcode的终端不支持颜色输出，sbt命令我更新了-x选项，在Xcode中的时候输入sbt -x禁用颜色输出

**Comment by geekonion** [comment]
好的，谢谢。
