### ISSUE TITLE
indexError: list index out of range

### ISSUE THREAD

**Issue by mydir2010** [4ch12dy/xia0LLDB#10]
raceback (most recent call last):
  File "/Users/aaabbb/xia0LLDB/src/debugme.py", line 43, in handle_command
    debugme(debugger)
  File "/Users/aaabbb/xia0LLDB/src/debugme.py", line 718, in debugme
    images = utils.get_all_image_of_app()
  File "/Users/aaabbb/xia0LLDB/src/utils.py", line 102, in get_all_image_of_app
    image_name = image_str.split(",")[1]
IndexError: list index out of range
[x] happy debugging~ kill antiDebug by xia0@2019

<img width="570" alt="图片" src="https://user-images.githubusercontent.com/64073444/79852228-fabc6480-83f8-11ea-8198-8e7af275b7b1.png">
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/64073444/79852310-14f64280-83f9-11ea-9b2a-cf5aa1e13962.png">

**Comment by 4ch12dy** [comment]
你更新到v2.5版本，我看下错误的日志

**Comment by mydir2010** [comment]
这个就是2.5版本的呀

**Comment by 4ch12dy** [comment]
更新到最新版本，里面会详细打出这个错误日志

**Comment by mydir2010** [comment]
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/64073444/79960764-60235a80-84b8-11ea-89b0-118e601d4334.png">
这个是更新到2.5的信息

**Comment by mydir2010** [comment]
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/64073444/79961062-c1e3c480-84b8-11ea-93a1-5034da7ec5a3.png">

**Comment by 4ch12dy** [comment]
2.6更新了应该没问题，顺便问下你这啥app

**Comment by mydir2010** [comment]
一个游戏，数独游戏
<img width="560" alt="图片" src="https://user-images.githubusercontent.com/64073444/79963865-81864580-84bc-11ea-8351-1e49dd5dd259.png">

**Comment by mydir2010** [comment]
这下可以了，谢谢大佬！
<img width="570" alt="图片" src="https://user-images.githubusercontent.com/64073444/79964357-286ae180-84bd-11ea-8747-7fe4ae86d1da.png">
