### ISSUE TITLE
dumpdecrypted -X failed

### ISSUE THREAD

**Issue by p845591892** [4ch12dy/xia0LLDB#13]
iPhone6
iOS12.3.1
Python3.6.8
MacOS

执行的指令和报错
(lldb) dumpdecrypted -X
[*] set breakpoint at CFBundleGetMainBundle
[*] will continue process and dump
[*] start execute dumpdecrypted
[*] delete all breakpoints
[-] failed to auto get main module, use -m option
[-] failed to auto get main module, use -m option
Traceback (most recent call last):
  File "/Users/shiro/Downloads/xia0LLDB/src/dumpdecrypted.py", line 51, in handle_command
    ret = dumpdecrypted(debugger)
  File "/Users/shiro/Downloads/xia0LLDB/src/dumpdecrypted.py", line 545, in dumpdecrypted
    images = utils.get_all_image_of_app()
  File "/Users/shiro/Downloads/xia0LLDB/src/utils.py", line 91, in get_all_image_of_app
    if app_path.startswith("/private"):
AttributeError: 'NoneType' object has no attribute 'startswith'

有点迷茫，想请教一下为什么会是执行python出问题，我对Python不是很熟

**Comment by 4ch12dy** [comment]
app是啥

**Comment by p845591892** [comment]
口袋48

**Comment by 4ch12dy** [comment]
我试了没问题，我猜你lldb以后都没连接上手机。先输入pcc命令。。。。

**Comment by p845591892** [comment]
代理报错
Requesting connecion to USB device handle 2 (serial: 37b786cf42c8b4fec387aabe31fb1cbcc961507f), port 1234
Error connecting to device: No such file or directory

lldb报错
(lldb) pcc
error: failed to get reply to handshake packet

感觉确实连不上，有什么连接的准备条件吗？
