### ISSUE TITLE
砸壳失败 

### ISSUE THREAD

**Issue by MrGuys** [4ch12dy/xia0LLDB#19]
6s，12.0系统
砸壳报错

`error: Couldn't lookup symbols:`
 ` __Z7strrchrUa9enable_ifIXLb1EEEPci`
 ` __Z6strchrUa9enable_ifIXLb1EEEPci`

`error: Couldn't lookup symbols:`
  `__Z7strrchrUa9enable_ifIXLb1EEEPci`
  `__Z6strchrUa9enable_ifIXLb1EEEPci`

`error: Couldn't lookup symbols:`
  `__Z7strrchrUa9enable_ifIXLb1EEEPci`
  `__Z6strchrUa9enable_ifIXLb1EEEPci`

`error: Couldn't lookup symbols:`
  `__Z7strrchrUa9enable_ifIXLb1EEEPci`
  `__Z6strchrUa9enable_ifIXLb1EEEPci`

`[*] Developed By xia0@2019`

**Comment by 4ch12dy** [comment]
App是啥

**Comment by MrGuys** [comment]
windy或者pokemon，都会这样

**Comment by 4ch12dy** [comment]
换设备吧，pokemon测试过的，没问题

**Comment by MrGuys** [comment]
好吧。。。。
