### ISSUE TITLE
sbt -f 结果出不来

### ISSUE THREAD

**Issue by Rico358097990** [4ch12dy/xia0LLDB#2]
见截图
![image](https://user-images.githubusercontent.com/16099174/61276161-10558b80-a7e2-11e9-8cff-f8b9eaf0cfe3.png)
![image](https://user-images.githubusercontent.com/16099174/61276225-30854a80-a7e2-11e9-862d-6e37566ebf46.png)

**Comment by 4ch12dy** [comment]
什么结果出不来？我看了下你目前的栈帧中不包含NewCenterWeather模块的符号，建议你先下一个NewCenterWeather中的断点，然后用sbt -f json_file 试下

**Comment by 4ch12dy** [comment]
> 见截图
> ![image](https://user-images.githubusercontent.com/16099174/61276161-10558b80-a7e2-11e9-8cff-f8b9eaf0cfe3.png)
> ![image](https://user-images.githubusercontent.com/16099174/61276225-30854a80-a7e2-11e9-862d-6e37566ebf46.png)

什么结果出不来？我看了下你目前的栈帧中不包含NewCenterWeather模块的符号，建议你先下一个NewCenterWeather中的断点，然后用sbt -f json_file 试下
