### ISSUE TITLE
与QT Creator程序冲突

### ISSUE THREAD

**Issue by wxq491216** [4ch12dy/xia0LLDB#24]
在mac版本上使用后，会导致QT Creator无法正常调试，有办法兼容这个问题么？

**Comment by 4ch12dy** [comment]
应该没有关系吧？

**Comment by wxq491216** [comment]
我确认过，把.lldbinit中添加的语句注释掉，QT Creator就能够正常用了，具体原因我也不是很清楚，查资料有提到过DefaultPythonVersion导致的，但确认了我本地值是2，有点奇怪。

**Comment by MustangYM** [comment]
## 确实与Qt Creator的debug不兼容
- Qt Creator 5.0.2
- QT5.15.2
- DefaultPythonVersion = 2（因为QT必须要设置为版本2才能debug，不知是否是这个原因，未知）
- xia0LLDB 3.1

## QT Error log
`[xia0LLDB] * Version: 3.1 
>[xia0LLDB] + Loading all scripts from /Users/apple/Downloads/xia0LLDB-master/src
>[xia0LLDB] * Finished 
>(lldb) script sys.path.insert(1, '/Applications/Qt Creator.app/Contents/Resources/debugger/')
>(lldb) script from lldbbridge import *
>Traceback (most recent call last):
>  File "<input>", line 1, in <module>
>  File "/Applications/Qt Creator.app/Contents/Resources/debugger/lldbbridge.py", line 35, in <module>
>    from utils import DebuggerStartMode, BreakpointType, TypeCode, LogChannel
>ImportError: cannot import name 'DebuggerStartMode' from 'utils' (/Users/apple/Downloads/xia0LLDB-master/src/utils.py)`
