### ISSUE TITLE
error: module importing failed: invalid syntax (sbt.py, line 166)   File "temp.py", line 1, in <module>

### ISSUE THREAD

**Issue by codesourse** [4ch12dy/xia0LLDB#4]
error: module importing failed: invalid syntax (sbt.py, line 166)
  File "temp.py", line 1, in <module>

报错了

**Comment by 4ch12dy** [comment]
你把完整的错误信息发出来看看，这看不很出来是什么原因

**Comment by No-Karma** [comment]
请问现在已经支持python3了吗，用不了很难受...

**Comment by 4ch12dy** [comment]
> 请问现在已经支持python3了吗，用不了很难受...

暂时没时间移植，新版mac系统不是可以修改成Python2吗

**Comment by No-Karma** [comment]
不知道是哪里出了问题  

➜  xia0LLDB-master lldb
error: module importing failed: invalid pathname
========
[traceOC]: trace ObjectC function call
	traceOC
	more usage, try "traceOC -h"
========
[xutil]: some util tool for debug, this command is flexable and some options maybe remove future
	xutil [-b addr, -s module, -l dylib]
	more usage, try "xutil -h"
error: module importing failed: invalid syntax (choose.py, line 274)
  File "temp.py", line 1, in <module>

error: module importing failed: Missing parentheses in call to 'print'. Did you mean print('please specify the param, for example: "-[UIView initWithFrame:]"')? (xbr.py, line 531)
  File "temp.py", line 1, in <module>

error: module importing failed: invalid syntax (dumpdecrypted.py, line 431)
  File "temp.py", line 1, in <module>

========
[debugme]: kill anti-debug in lldb
	debugme
	more usage, try "debugme -h"
========
[info]: get basic info of process/function/module/address/...
	info [-m moduleName, -a address, -f funtionName, -u UserDefaults]
	more usage, try "info -h"
error: module importing failed: invalid syntax (sbt.py, line 166)
  File "temp.py", line 1, in <module>

**Comment by 4ch12dy** [comment]
Duplicate of #3 
这就是新系统Python3的问题，执行下面的代码指定lldb为Python2解释器就行了
```
defaults write com.apple.dt.lldb DefaultPythonVersion 2
```

**Comment by No-Karma** [comment]
额，理解错了，在另外一个issue里面看到这句话，以为这句是导致部分问题的原因

**Comment by codesourse** [comment]
可以了，三克油
